/**
 * Rich synthetic CMDB for PHISH SLAYER — Enterprise Asset Management & dependency mesh.
 * Interconnects departments, personnel hierarchy, multi-cloud tooling, CI/CD, finance/legal,
 * and five scenario profiles (budget spill, DevOps outage, secret-in-CI, contractor offboarding, CMDB sync).
 * All identifiers are fictional; no real org data.
 */

export const mockCmdb = {
  company: {
    id: "corp-northwind-labs",
    name: "Northwind Labs (Synthetic)",
    cmdbVersion: "CMDB-Schema-7.2",
    viewerInstance: "CMDB-VIEW-PROD-01",
  },

  /** Five core departments + executive office mesh */
  departments: [
    {
      departmentId: "DEPT-PLAT",
      name: "Core Platform Engineering",
      costCenter: "CC-4400-PLAT",
      headcountBudgeted: 48,
      primaryLocation: "SEA-01",
    },
    {
      departmentId: "DEPT-CLOUD",
      name: "Cloud Infrastructure",
      costCenter: "CC-4410-CLOUD",
      headcountBudgeted: 32,
      primaryLocation: "IAD-02",
    },
    {
      departmentId: "DEPT-DEVOPS",
      name: "DevOps & CI/CD",
      costCenter: "CC-4420-DEVX",
      headcountBudgeted: 26,
      primaryLocation: "DFW-01",
    },
    {
      departmentId: "DEPT-FIN",
      name: "Enterprise Finance Ops",
      costCenter: "CC-2100-FIN",
      headcountBudgeted: 18,
      primaryLocation: "NYC-01",
    },
    {
      departmentId: "DEPT-LEGAL",
      name: "Legal & Compliance",
      costCenter: "CC-3300-LEG",
      headcountBudgeted: 12,
      primaryLocation: "SFO-02",
    },
    {
      departmentId: "DEPT-EXEC",
      name: "Executive Office — Technology",
      costCenter: "CC-0001-EXEC",
      headcountBudgeted: 6,
      primaryLocation: "SFO-HQ",
    },
  ],

  /**
   * Five scenario templates — data mesh must support each narrative.
   */
  scenarioProfiles: [
    {
      profileId: "P1_BUDGET_SPILL",
      name: "Multi-Cloud Budget Spill",
      summary:
        "Auto-scaling footprint across GCP + AWS with dedicated billing; supports urgent 300% spike on named resources.",
      attackVector: "Finance + infra impersonation; exact billing account and bucket identifiers.",
    },
    {
      profileId: "P2_DEVOPS_OUTAGE",
      name: "DevOps / Microservice Outage",
      summary: "Core microservice mapped to DataDog monitor namespace + GitHub HEAD; emergency failover to primary engineer.",
      attackVector: "Pager + repo commit correlation; on-call pressure.",
    },
    {
      profileId: "P3_PIPELINE_SECRET",
      name: "Hardcoded Secret Exposure (CI/CD)",
      summary: "Repository module paths and workflow files for automated security-advisory pretext.",
      attackVector: "Fake GHA / pipeline scanner alert with repo-relative paths.",
    },
    {
      profileId: "P4_CONTRACTOR_OFFBOARD",
      name: "Imminent Contractor Offboarding",
      summary: "Short-term contractor with fixed end date; peer handover of sensitive artifacts before expiry.",
      attackVector: "Transition anxiety + peer-to-peer file transfer urgency.",
    },
    {
      profileId: "P5_CMDB_VIEWER_SYNC",
      name: "System Viewer Metadata Synch",
      summary: "Asset registry with concrete IDs and version lineage for ITAM compliance-style lures.",
      attackVector: "CMDB viewer / reconciliation job with authoritative asset IDs.",
    },
  ],

  personnel: [
    {
      employeeId: "EMP-C01",
      fullName: "Elena Marquez",
      workEmail: "e.marquez@northwind-labs.example",
      directPhone: "+1-555-0301",
      nationalIdMasked: "***-**-1100",
      homeCity: "Ashburn",
      role: "Director of Cloud Architecture",
      roleArchetype: "executive_strategic_lead",
      departmentId: "DEPT-CLOUD",
      department: "Cloud Infrastructure",
      employmentType: "FTE",
      reportsToEmployeeId: "EMP-X01",
      sponsorEmployeeId: null,
      peerEmployeeIds: ["EMP-1001", "EMP-D01"],
      projectIds: ["PRJ-AURORA-BILL", "PRJ-METACORE"],
      clearanceLevel: "L4",
      preferredDeliveryVector: "Email",
      emotionalArchetype: "portfolio_risk_ownership",
      primaryTechTheme: "multi_cloud_governance",
      simulationHooks: ["Board-level cost narratives", "Cross-cloud reserved capacity commitments"],
    },
    {
      employeeId: "EMP-X01",
      fullName: "Jordan Blake",
      workEmail: "j.blake@northwind-labs.example",
      directPhone: "+1-555-0001",
      nationalIdMasked: "***-**-0007",
      homeCity: "San Francisco",
      role: "CTO & Executive Sponsor",
      roleArchetype: "executive_strategic_lead",
      departmentId: "DEPT-EXEC",
      department: "Executive Office — Technology",
      employmentType: "FTE",
      reportsToEmployeeId: null,
      sponsorEmployeeId: null,
      peerEmployeeIds: ["EMP-C01"],
      projectIds: ["PRJ-AURORA-BILL", "PRJ-TACHYON-SRE", "PRJ-METACORE"],
      clearanceLevel: "L5",
      preferredDeliveryVector: "Email",
      emotionalArchetype: "board_visibility_stress",
      primaryTechTheme: "portfolio_governance",
      simulationHooks: ["Revenue-impacting outage language"],
    },
    {
      employeeId: "EMP-1001",
      fullName: "Sarah Jenkins",
      workEmail: "s.jenkins@northwind-labs.example",
      directPhone: "+1-555-0100",
      nationalIdMasked: "***-**-4321",
      homeCity: "Seattle",
      role: "Principal Product Manager — Platform",
      roleArchetype: "project_owner",
      departmentId: "DEPT-PLAT",
      department: "Core Platform Engineering",
      employmentType: "FTE",
      reportsToEmployeeId: "EMP-X01",
      sponsorEmployeeId: "EMP-X01",
      peerEmployeeIds: ["EMP-1002", "EMP-1004", "EMP-F01"],
      projectIds: ["PRJ-AURORA-BILL", "PRJ-TACHYON-SRE", "PRJ-TRANSIT-OUT"],
      clearanceLevel: "L3",
      preferredDeliveryVector: "Slack",
      emotionalArchetype: "responsibility_overload",
      primaryTechTheme: "multi_cloud_ops",
      simulationHooks: ["SOC2 adjacent delivery pressure", "Cross-team dependency mapping"],
    },
    {
      employeeId: "EMP-1002",
      fullName: "Marcus Thorne",
      workEmail: "m.thorne@northwind-labs.example",
      directPhone: "+1-555-0102",
      nationalIdMasked: "***-**-1188",
      homeCity: "Austin",
      role: "Distinguished Engineer — Runtime",
      roleArchetype: "lead_engineer",
      departmentId: "DEPT-PLAT",
      department: "Core Platform Engineering",
      employmentType: "FTE",
      reportsToEmployeeId: "EMP-1001",
      sponsorEmployeeId: "EMP-X01",
      peerEmployeeIds: ["EMP-1001", "EMP-1003", "EMP-D01"],
      projectIds: ["PRJ-TACHYON-SRE", "PRJ-SEALRUNNER", "PRJ-METACORE"],
      clearanceLevel: "L4",
      preferredDeliveryVector: "Email",
      emotionalArchetype: "hero_complex_burnout",
      primaryTechTheme: "kubernetes_gitops",
      simulationHooks: ["Primary on-call for payments edge", "GitHub CODEOWNER for critical paths"],
    },
    {
      employeeId: "EMP-D01",
      fullName: "Riley Chen",
      workEmail: "r.chen@northwind-labs.example",
      directPhone: "+1-555-0401",
      nationalIdMasked: "***-**-2202",
      homeCity: "Dallas",
      role: "Principal DevOps Engineer",
      roleArchetype: "lead_engineer",
      departmentId: "DEPT-DEVOPS",
      department: "DevOps & CI/CD",
      employmentType: "FTE",
      reportsToEmployeeId: "EMP-1002",
      sponsorEmployeeId: "EMP-C01",
      peerEmployeeIds: ["EMP-1002"],
      projectIds: ["PRJ-SEALRUNNER", "PRJ-TACHYON-SRE"],
      clearanceLevel: "L3",
      preferredDeliveryVector: "Slack",
      emotionalArchetype: "pipeline_guardian",
      primaryTechTheme: "cicd_supply_chain",
      simulationHooks: ["Owns OIDC trust between GHA and GCP WIF", "Secrets scanning policy exceptions"],
    },
    {
      employeeId: "EMP-1003",
      fullName: "Alex Rivera",
      workEmail: "a.rivera.contract@northwind-labs.example",
      directPhone: "+1-555-0199",
      nationalIdMasked: null,
      homeCity: "Denver",
      role: "Staff Engineer (Contract)",
      roleArchetype: "internal_contract_employee",
      departmentId: "DEPT-PLAT",
      department: "Core Platform Engineering",
      employmentType: "CONTRACT",
      contractVendor: "Vertex Staffing LLC",
      contractEndDate: "2026-06-15",
      reportsToEmployeeId: "EMP-1001",
      sponsorEmployeeId: "EMP-1001",
      peerEmployeeIds: ["EMP-1002", "EMP-1004"],
      projectIds: ["PRJ-TRANSIT-OUT", "PRJ-AURORA-BILL"],
      clearanceLevel: "L2",
      preferredDeliveryVector: "Teams",
      emotionalArchetype: "contractor_inclusion_anxiety",
      primaryTechTheme: "data_handoff_paths",
      simulationHooks: ["Imminent offboarding — knowledge transfer windows", "Shared drive ACL cleanup"],
    },
    {
      employeeId: "EMP-1004",
      fullName: "Priya Desai",
      workEmail: "p.desai@northwind-labs.example",
      directPhone: "+1-555-0144",
      nationalIdMasked: "***-**-2201",
      homeCity: "Chicago",
      role: "Staff SRE — Observability",
      roleArchetype: "lead_engineer",
      departmentId: "DEPT-PLAT",
      department: "Core Platform Engineering",
      employmentType: "FTE",
      reportsToEmployeeId: "EMP-1002",
      sponsorEmployeeId: "EMP-X01",
      peerEmployeeIds: ["EMP-1001", "EMP-1002", "EMP-D01"],
      projectIds: ["PRJ-TACHYON-SRE", "PRJ-METACORE"],
      clearanceLevel: "L3",
      preferredDeliveryVector: "Email",
      emotionalArchetype: "procedure_pride",
      primaryTechTheme: "observability_sre",
      simulationHooks: ["Datadog SLO burn alerts", "Runbook version discipline"],
    },
    {
      employeeId: "EMP-F01",
      fullName: "James Okonkwo",
      workEmail: "j.okonkwo@northwind-labs.example",
      directPhone: "+1-555-0501",
      nationalIdMasked: "***-**-3301",
      homeCity: "New York",
      role: "Director — Cloud Cost Governance",
      roleArchetype: "project_owner",
      departmentId: "DEPT-FIN",
      department: "Enterprise Finance Ops",
      employmentType: "FTE",
      reportsToEmployeeId: "EMP-X01",
      sponsorEmployeeId: "EMP-X01",
      peerEmployeeIds: ["EMP-1001", "EMP-L01"],
      projectIds: ["PRJ-AURORA-BILL"],
      clearanceLevel: "L3",
      preferredDeliveryVector: "Email",
      emotionalArchetype: "quarter_close_pressure",
      primaryTechTheme: "finops_billing",
      simulationHooks: ["Billing anomaly committee", "CFO readout decks"],
    },
    {
      employeeId: "EMP-L01",
      fullName: "Morgan Tate",
      workEmail: "m.tate@northwind-labs.example",
      directPhone: "+1-555-0601",
      nationalIdMasked: "***-**-4401",
      homeCity: "San Francisco",
      role: "Senior Counsel — Data Residency",
      roleArchetype: "project_owner",
      departmentId: "DEPT-LEGAL",
      department: "Legal & Compliance",
      employmentType: "FTE",
      reportsToEmployeeId: "EMP-X01",
      sponsorEmployeeId: "EMP-X01",
      peerEmployeeIds: ["EMP-F01"],
      projectIds: ["PRJ-METACORE", "PRJ-TRANSIT-OUT"],
      clearanceLevel: "L3",
      preferredDeliveryVector: "Teams",
      emotionalArchetype: "regulatory_scrutiny",
      primaryTechTheme: "data_residency",
      simulationHooks: ["Subprocessor change notices", "DPA amendment cycles"],
    },
    {
      employeeId: "EMP-L99",
      fullName: "Jamie Frost",
      workEmail: "j.frost.contract@northwind-labs.example",
      directPhone: "+1-555-0699",
      nationalIdMasked: null,
      homeCity: "Boston",
      role: "Compliance Analyst (Contract)",
      roleArchetype: "internal_contract_employee",
      departmentId: "DEPT-LEGAL",
      department: "Legal & Compliance",
      employmentType: "CONTRACT",
      contractVendor: "Hudson Legal Partners",
      contractEndDate: "2026-06-15",
      reportsToEmployeeId: "EMP-L01",
      sponsorEmployeeId: "EMP-L01",
      peerEmployeeIds: [],
      projectIds: ["PRJ-METACORE"],
      clearanceLevel: "L2",
      preferredDeliveryVector: "Email",
      emotionalArchetype: "audit_fatigue",
      primaryTechTheme: "evidence_management",
      simulationHooks: ["Parallel contract end with Alex Rivera — dual handover risk"],
    },
  ],

  projects: [
    {
      projectId: "PRJ-AURORA-BILL",
      name: "Aurora FinOps Mesh",
      status: "ACTIVE",
      departmentIds: ["DEPT-CLOUD", "DEPT-FIN", "DEPT-PLAT"],
      scenarioProfileIds: ["P1_BUDGET_SPILL"],
      ownerEmployeeId: "EMP-F01",
      leadDevEmployeeId: "EMP-1002",
      description:
        "Cross-cloud autoscaling mesh with consolidated FinOps reporting; subject to anomalous spend alerts.",
      billingSyntheticIncident: {
        spikePctVs7dAvg: 300,
        windowHours: 6,
        primaryResourceLabel: "GCE_AS_NW_ORDERS_API_ASG",
        narrativeHook: "Unthrottled autoscaler on orders-api fleet correlated with bad cache key rollout.",
      },
      integrationRefs: {
        gcp: {
          gcp_billing_account_id: "BILL-992-GCP",
          projectId: "nw-aurora-prod-771",
          projectNumber: "948102773441",
          computeInstanceName: "gce-orders-api-m5-az-a-07",
          region: "us-central1",
          bigqueryDataset: "finops_curated_prod",
        },
        aws: {
          aws_s3_bucket: "prod-data-lake-v2",
          dynamodbTable: "DYNAMO-ORDERS-EVENTS-PROD",
          ec2AutoScalingGroup: "asg-orders-edge-prod-use1-09",
          region: "us-east-1",
          costAllocationTag: "cost-center/CC-4400-PLAT",
        },
        datadog: {
          metricNamespace: "gcp.billing.export",
          dashboardId: "dash-finops-aurora-992",
          monitorIds: ["alert.finops.gcp.daily_spend_anomaly"],
        },
        github: {
          org: "northwind-labs",
          repo: "aurora-finops-mesh",
          defaultBranch: "main",
          lastCommitSha: "a91c3d7e2b4f8c0d1e6a5b3c9d2e7f1a0b4c8d6",
        },
      },
      criticalAssets: ["AST-AUR-01", "AST-AUR-02", "AST-AUR-03"],
    },
    {
      projectId: "PRJ-TACHYON-SRE",
      name: "Tachyon Payments Edge",
      status: "ACTIVE",
      departmentIds: ["DEPT-PLAT", "DEPT-DEVOPS"],
      scenarioProfileIds: ["P2_DEVOPS_OUTAGE"],
      ownerEmployeeId: "EMP-1001",
      leadDevEmployeeId: "EMP-1002",
      description:
        "Primary microservice edge for card-tokenization; hard-wired to SLO monitors and GitOps release train.",
      integrationRefs: {
        datadog: {
          metricNamespace: "nw.payments.edge",
          dashboardId: "dash-tachyon-sre-prod",
          monitorIds: ["alert.prod.db.latency", "slo.burn.tachyon.p99.error_budget"],
          primaryMonitorHumanName: "alert.prod.db.latency",
        },
        github: {
          org: "northwind-labs",
          repo: "payments-edge",
          defaultBranch: "release/tachyon-2.8",
          lastCommitSha: "4f0e9c2a1d8b7e6c5a3b2d1e0f9c8b7a6d5e4f3",
        },
        aws: {
          ec2AutoScalingGroup: "asg-payments-edge-prod-use1-03",
          region: "us-east-1",
        },
      },
      criticalAssets: ["AST-TAC-01", "AST-TAC-02"],
    },
    {
      projectId: "PRJ-SEALRUNNER",
      name: "Sealrunner Supply Chain",
      status: "ACTIVE",
      departmentIds: ["DEPT-DEVOPS"],
      scenarioProfileIds: ["P3_PIPELINE_SECRET"],
      ownerEmployeeId: "EMP-D01",
      leadDevEmployeeId: "EMP-D01",
      description:
        "GitHub Actions OIDC to GCP WIF; module graph includes legacy plaintext loader flagged by scanners.",
      integrationRefs: {
        github: {
          org: "northwind-labs",
          repo: "sealrunner-pipelines",
          defaultBranch: "main",
          lastCommitSha: "7b2c9d1e0f8a6b5c4d3e2f1a0b9c8d7e6f5a4b3",
        },
        cicdExposureMap: {
          workflowPath: ".github/workflows/release.yml",
          reusableWorkflowPath: ".github/workflows/_reusable_sign_and_publish.yaml",
          modulePaths: [
            "packages/auth/src/legacy_token_loader.ts",
            "modules/secrets/loader.ts",
            "infra/terraform/modules/wif_pool/main.tf",
          ],
          artifactRegistry: "us-docker.pkg.dev/nw-build/sealrunner",
        },
        gcp: {
          gcp_billing_account_id: "BILL-992-GCP",
          projectId: "nw-sealrunner-build-009",
          projectNumber: "112233445566",
        },
      },
      criticalAssets: ["AST-SEAL-01", "AST-SEAL-02"],
    },
    {
      projectId: "PRJ-TRANSIT-OUT",
      name: "Transit Knowledge Offboarding",
      status: "ACTIVE",
      departmentIds: ["DEPT-PLAT", "DEPT-LEGAL"],
      scenarioProfileIds: ["P4_CONTRACTOR_OFFBOARD"],
      ownerEmployeeId: "EMP-1001",
      leadDevEmployeeId: "EMP-1002",
      description:
        "Controlled wind-down of contractor access; artifact handover checklist tied to HRIS contract end dates.",
      contractorHandoff: {
        primaryContractorEmployeeId: "EMP-1003",
        contractEndDate: "2026-06-15",
        peerRecipientEmployeeId: "EMP-1004",
        hrisCaseId: "HRIS-OFFBOARD-2026-Q2-8841",
      },
      integrationRefs: {
        github: {
          org: "northwind-labs",
          repo: "transit-handoff-pack",
          defaultBranch: "main",
          lastCommitSha: "0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9",
        },
      },
      criticalAssets: ["AST-TRN-01", "AST-TRN-02", "AST-TRN-03"],
    },
    {
      projectId: "PRJ-METACORE",
      name: "MetaCore CMDB Reconciliation",
      status: "ACTIVE",
      departmentIds: ["DEPT-PLAT", "DEPT-LEGAL", "DEPT-CLOUD"],
      scenarioProfileIds: ["P5_CMDB_VIEWER_SYNC"],
      ownerEmployeeId: "EMP-L01",
      leadDevEmployeeId: "EMP-1002",
      description:
        "Authoritative asset registry sync job for ITAM; drives compliance attestations and viewer metadata exports.",
      cmdbViewerJob: {
        jobName: "CMDB_VIEWER_DELTA_SYNC",
        scheduleCron: "15 */4 * * *",
        lastRunId: "RUN-CI-7734-PROD-20260522T0415Z",
        reconciliationScope: "PROD-EAST + FIN-SENSITIVE",
      },
      integrationRefs: {
        github: {
          org: "northwind-labs",
          repo: "metacore-cmdb-sync",
          defaultBranch: "main",
          lastCommitSha: "9e8d7c6b5a4938271605f4e3d2c1b0a9f8e7d6c5",
        },
      },
      criticalAssets: ["AST-META-992", "AST-META-CI7734", "AST-META-03"],
    },
  ],

  assets: [
    {
      assetId: "AST-AUR-01",
      projectId: "PRJ-AURORA-BILL",
      displayName: "gcp_budget_config.json",
      versionLabel: "v3.2.1",
      pathHint: "gs://nw-aurora-config/billing/gcp_budget_config.json",
      classification: "CONFIDENTIAL",
      systemId: "CI-8821-CONFIG",
    },
    {
      assetId: "AST-AUR-02",
      projectId: "PRJ-AURORA-BILL",
      displayName: "infra_topology_final.dwg",
      versionLabel: "R12",
      pathHint: "s3://prod-data-lake-v2/diagrams/infra_topology_final.dwg",
      classification: "INTERNAL",
      systemId: "Asset ID-7781",
    },
    {
      assetId: "AST-AUR-03",
      projectId: "PRJ-AURORA-BILL",
      displayName: "Schema_v4.pdf",
      versionLabel: "v4.0.2",
      pathHint: "s3://prod-data-lake-v2/contracts/Schema_v4.pdf",
      classification: "INTERNAL",
      systemId: "Asset ID-992",
    },
    {
      assetId: "AST-TAC-01",
      projectId: "PRJ-TACHYON-SRE",
      displayName: "deployment_manifest.yaml",
      versionLabel: "2.8.0-rc3",
      pathHint: "github:northwind-labs/payments-edge/k8s/deployment_manifest.yaml",
      classification: "INTERNAL",
      systemId: "CI-9910-K8S",
    },
    {
      assetId: "AST-TAC-02",
      projectId: "PRJ-TACHYON-SRE",
      displayName: "failover_playbook_TACHYON.md",
      versionLabel: "2026-Q2",
      pathHint: "confluence:/SRE/failover_playbook_TACHYON.md",
      classification: "INTERNAL",
      systemId: "Asset ID-4412",
    },
    {
      assetId: "AST-SEAL-01",
      projectId: "PRJ-SEALRUNNER",
      displayName: "release.yml",
      versionLabel: "sha-7b2c9d1",
      pathHint: "github:northwind-labs/sealrunner-pipelines/.github/workflows/release.yml",
      classification: "CONFIDENTIAL",
      systemId: "CI-2201-GHA",
    },
    {
      assetId: "AST-SEAL-02",
      projectId: "PRJ-SEALRUNNER",
      displayName: "legacy_token_loader.ts",
      versionLabel: "module@payments-auth-3.4",
      pathHint: "github:northwind-labs/sealrunner-pipelines/packages/auth/src/legacy_token_loader.ts",
      classification: "CONFIDENTIAL",
      systemId: "CI-2202-SRC",
    },
    {
      assetId: "AST-TRN-01",
      projectId: "PRJ-TRANSIT-OUT",
      displayName: "Contractor_Knowledge_Transfer_Checklist.xlsx",
      versionLabel: "rev-F",
      pathHint: "sharepoint:/HR/Contractor_Knowledge_Transfer_Checklist.xlsx",
      classification: "CONFIDENTIAL",
      systemId: "Asset ID-6601",
    },
    {
      assetId: "AST-TRN-02",
      projectId: "PRJ-TRANSIT-OUT",
      displayName: "ACL_Revocation_Schedule.csv",
      versionLabel: "2026-06-10",
      pathHint: "gs://nw-transit-legal/ACL_Revocation_Schedule.csv",
      classification: "CONFIDENTIAL",
      systemId: "CI-6610-ACL",
    },
    {
      assetId: "AST-TRN-03",
      projectId: "PRJ-TRANSIT-OUT",
      displayName: "Peer_Handoff_Signoff.pdf",
      versionLabel: "v1",
      pathHint: "sharepoint:/Legal/Peer_Handoff_Signoff.pdf",
      classification: "INTERNAL",
      systemId: "Asset ID-6602",
    },
    {
      assetId: "AST-META-992",
      projectId: "PRJ-METACORE",
      displayName: "CMDB_Viewer_Metadata_export.ndjson",
      versionLabel: "build-20260522.0415",
      pathHint: "s3://nw-cmdb-exports/viewer/CMDB_Viewer_Metadata_export.ndjson",
      classification: "CONFIDENTIAL",
      systemId: "Asset ID-992",
    },
    {
      assetId: "AST-META-CI7734",
      projectId: "PRJ-METACORE",
      displayName: "reconciliation_manifest.json",
      versionLabel: "CI-7734-PROD",
      pathHint: "s3://nw-cmdb-exports/jobs/CI-7734-PROD/reconciliation_manifest.json",
      classification: "INTERNAL",
      systemId: "CI-7734-PROD",
    },
    {
      assetId: "AST-META-03",
      projectId: "PRJ-METACORE",
      displayName: "ITAM_Control_Matrix_v9.xlsx",
      versionLabel: "v9.1",
      pathHint: "sharepoint:/Compliance/ITAM_Control_Matrix_v9.xlsx",
      classification: "INTERNAL",
      systemId: "Asset ID-7735",
    },
  ],
};

export function findPersonnelById(employeeId) {
  return mockCmdb.personnel.find((p) => p.employeeId === employeeId) ?? null;
}

export function findDepartmentById(departmentId) {
  return mockCmdb.departments.find((d) => d.departmentId === departmentId) ?? null;
}

export function listEmployeeSummaries() {
  return mockCmdb.personnel.map((p) => ({
    employeeId: p.employeeId,
    fullName: p.fullName,
    role: p.role,
    department: p.department,
    departmentId: p.departmentId,
    employmentType: p.employmentType,
    preferredDeliveryVector: p.preferredDeliveryVector,
    emotionalArchetype: p.emotionalArchetype ?? null,
    primaryTechTheme: p.primaryTechTheme ?? null,
    roleArchetype: p.roleArchetype ?? null,
    contractEndDate: p.contractEndDate ?? null,
  }));
}
